theme: minima


title: Jaderest's Blog
author: Jaderest

show_downloads: true

# 导航栏链接
# header_pages:
#   - about.md
#   - projects.md
#   - publications.md
#   - contact.md

# 博客的社交媒体信息
social_links:
  email: jaderest233@outlook.com
  github: Jaderest

# 评论系统
disqus:
  shortname: jaderest